### ISSUE TITLE
Improve FOV support

### ISSUE THREAD

**Issue by ChillGenXer** [ChillGenXer/TimeControlPlus#2]
The tree model gets skewed on extreme FOV's, need to find a way to make the model stable.

**Comment by ttr** [comment]
Not sure if this is related, but that tree model is blinking like crazy - like you would reload/re-render image every update.

**Comment by ChillGenXer** [comment]
Possibly related.  I am using the 3d model of an apple tree from the game so I am getting some challenges with this rather than using custom image files.

**Comment by ChillGenXer** [comment]
This has now been resolved in 0.3.5.
