### ISSUE TITLE
Change Time Label to WT from UTC

### ISSUE THREAD

**Issue by ChillGenXer** [ChillGenXer/TimeControlPlus#3]
[salzlaender](https://steamcommunity.com/profiles/76561198080636573) 27 Nov @ 3:40pm 
You probably get the UTC built-in, but can you change that to "world time" or so? It freakes me out that the stone age has UTC :D
More importnatly that would also hopefully make people realize that the timer is not off when it shows 2 am in bright sunshine.

**Comment by ttr** [comment]
or use UT (as universal time) as some other games (KSP comes to mind) use it. If game engine supports, LT (local) time might be good. to display instead.

**Comment by ChillGenXer** [comment]
To the original issue I copied in here from a Steam Workshop comment there is only so much I am willing to do with this one.  I won't be getting into implementing time zones and such so the sunrise/set happens when you think it should happen, as that's just way too much effort for a simple mod, the time is really meant to show the passage of what the game engine considers a day.  @ttr I think labelling it UT would be a good compromise.

**Comment by ChillGenXer** [comment]
I changed the label to "WT" (World Time), it will be in the next update.
