### ISSUE TITLE
Year/Day is hardcoded for 8 days per year

### ISSUE THREAD

**Issue by ttr** [ChillGenXer/TimeControlPlus#4]
Hi,
You can change in game length of year (and day) in config.xml inside save game.

Your code does modulo 8 on year/day calculation, but in fact it should calculate it from yearSpeed (IIRC it will be 1/yearSpeed). Since this rarely will be integer, rounding it to nearest would be good compromise.

**Comment by ChillGenXer** [comment]
Thanks for the feedback!  I will take a look at this and see what I can do with this, want to make sure it works correctly when multiplayer comes out and server owners can more easily change these parameters.

**Comment by ChillGenXer** [comment]
Changed the calculation to replace "8" with yearLength\dayLength, so this should use these two configurable parameters to determine how many days are actually in the year.  Change will be in 0.4.1.
